extends: spectral:oas
rules:
  oas3-unused-component: hint
  components-camel-case:
    description: Components MUST be written in UpperCamelCase
    message: '{{property}} is not UpperCamelCase.'
    recommended: true
    type: style
    given: '$.components.schemas'
    then:
      field: "@key"
      function: pattern
      functionOptions:
        match: '^([A-Z][a-z0-9]*)+$'
  properties-camel-case:
    description: All JSON Schema properties MUST follow lowerCamelCase.
    severity: warn
    recommended: true
    message: '{{property}} MUST follow lowerCamelCase.'
    given: '$.components.schemas..properties'
    then:
      field: "@key"
      function: pattern
      functionOptions:
        match: '^([a-z][A-Za-z0-9]*)+$'
  operationIds-camel-case:
    description: Operation IDs MUST be written in lowerCamelCase
    message: '{{property}} is not lowerCamelCase.'
    recommended: true
    type: style
    given: '$.paths.*[?( @property === ''get'' || @property === ''put'' || @property === ''post'' || @property === ''delete'' || @property === ''options'' || @property === ''head'' || @property === ''patch'' || @property === ''trace'' )]'
    then:
      field: operationId
      function: pattern
      functionOptions:
        match: '^([a-z][A-Za-z0-9]*)+$'
  request-GET-no-body:
    description: A `GET` request MUST NOT accept a `body` parameter
    severity: error
    recommended: true
    given: $.paths..get.parameters..in
    then:
      function: pattern
      functionOptions:
        notMatch: /^body$/
